on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
      - name: SetUpPython
        with:
          python-version: 3.7

      - name: sendwx
        run: mvn -B package --file main.py

